// Stephen Donchez
// Dr. Wang
// ECE 8448-DL1
// 18 March 2020

/******************************************************************************
* main.c -	main routine and configuration subroutines for Homework
*			Assignment 6, part 1. See README.md for assignment description.
******************************************************************************/

#include "include/tone.h"           //defines notes
#include "intelfpgaup/audio.h"      //intel provided audio interface
#include <math.h>                   //standard c math library

#define PI (4.0 * (atan(1.0)))      //since M_PI isn't actually standardized

void play_note(double note, int num_samples);           //main.c
double build_sample(int current_sample, double note);   //main.c
void write_sample(double sample);                       //main.c

/******************************************************************************
 * main: Configures audio codec and plays the tones specified in the assignment
 *       decription.
 *
 * @param	N/A
 * @returns	N/A
 * @note	N/A
 * @see		full description of program functionality in README.md
 *          Intel's "Using Linux on DE-Series Boards
 *****************************************************************************/
int main(void)
{
    int tone_length = 300;  //miliseconds
    int num_samples = tone_length / 1000.0 * MAX_SAMPLING_RATE; //from audio.h


    audio_open();                       //audio.h - open connection with codec
    audio_init();                       //audio.h - configure codec
    audio_rate(MAX_SAMPLING_RATE);      //audio.h - set sample rate to 48k


    //play notes for specified duration
    play_note(LOWERC, num_samples);
    play_note(CSHARP, num_samples);
    play_note(D, num_samples);
    play_note(DSHARP, num_samples);
    play_note(E, num_samples);
    play_note(F, num_samples);
    play_note(FSHARP, num_samples);
    play_note(G, num_samples);
    play_note(GSHARP, num_samples);
    play_note(A, num_samples);
    play_note(ASHARP, num_samples);
    play_note(B, num_samples);
    play_note(UPPERC, num_samples);

    audio_close();                      //audio.h - close connection with codec  
    return 0;
} //main

/******************************************************************************
 * play_note: builds and outputs the apropriate number of samples to generate
 *            the desired note for the desired length of time
 * @param	note: the note to be played, passed by frequency, defined in tone.h
 * @param   num_samples: number of samples to generate, computed in main
 * @returns	N/A
 * @note    N/A
 * @see		N/A
 *****************************************************************************/
void play_note(double note, int num_samples)
{
    for(int current_sample = 0; current_sample < num_samples; current_sample++)
    {
        double sample = build_sample(current_sample, note); //main.c
        write_sample(sample);
    } //for
} //play_note

/******************************************************************************
 * build_sample: builds the current sample from the sin wave
 * @param	note: the note to be played, passed by frequency, defined in tone.h
 * @param   current_sample: the current sample in the sample set (where in the
                sin wave the sample falls
 * @returns	N/A
 * @note    N/A
 * @see		Intel's "Using Linux on DE-Series Boards
 *****************************************************************************/
double build_sample(int current_sample, double note)
{
    return 
        (MAX_VOLUME * sin(note * current_sample / MAX_SAMPLING_RATE * 2 * PI));
} //build_sample

/******************************************************************************
 * write_sample: writes the current sample to the audio device
 * @param	sample: the current sample as generated by build_sample
 * @returns	N/A
 * @note    N/A
 * @see		Intel's "Using Linux on DE-Series Boards
 *****************************************************************************/
void write_sample(double sample)
{
    audio_wait_write();         //audio.h
    audio_write_left(sample);   //audio.h
    audio_write_right(sample);  //audio.h
} //write_sample